"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os as _os
import pathlib as _pathlib

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = _pathlib.Path(__file__).resolve().parent.parent.parent


# Python Ops
EXTRA_PYTHON_PATH = [
    BASE_DIR / 'GET3D',
]


# Pytorch Ops
TORCH_ENABLED = bool(int(_os.getenv("TORCH_ENABLED", 1)))

TORCH_WARM_UP_ITER = int(_os.getenv("TORCH_WARM_UP_ITER", 10))

TORCH_WITHOUT_CUSTOM_OPS_COMPILE = bool(int(_os.getenv("TORCH_WITHOUT_CUSTOM_OPS_COMPILE", 0)))

TORCH_DEVICE = _os.getenv("TORCH_DEVICE", "cuda:0")

TORCH_WEIGHT_PATH = _os.getenv("TORCH_WEIGHT_PATH", BASE_DIR / "weights/shapenet_car.pt")  # TODO

MODEL_OPTS = {  # Compatible with script arguments
    'latent_dim': 512,
    'one_3d_generator': True,
    'deformation_multiplier': 1.,
    'use_style_mixing': True,
    'dmtet_scale': 1.,  # TODO
    'feat_channel': 16,
    'mlp_latent_channel': 32,
    'tri_plane_resolution': 256,
    'n_views': 1,
    'render_type': 'neural_render',  # or 'spherical_gaussian'
    'use_tri_plane': True,
    'tet_res': 90,
    'geometry_type': 'conv3d',
    'data_camera_mode': 'shapenet_car',  # TODO
    'n_implicit_layer': 1,
    'cbase': 32768,
    'cmax': 512,
    'fp32': False
}

TORCH_SEED = 0

TORCH_RESOLUTION = 1024  # Image Resolution


# Application definition

INSTALLED_APPS = [

    # Built-in Contrib Apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Rest Framework Apps and Extensions
    'rest_framework',
    'drf_yasg',
    'django_extensions',
    'corsheaders',

    # User-Apps
    'studio_YAIVERSE.apps.accounts',
    'studio_YAIVERSE.apps.main',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'studio_YAIVERSE.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'studio_YAIVERSE.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'attachment'

FILE_UPLOAD_MAX_MEMORY_SIZE = 128 << 20  # 100 MB

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Extra Settings

AUTHENTICATION_BACKENDS = [
    # Built-in Backend
    'django.contrib.auth.backends.ModelBackend',
]

# LOGIN_URL = '/accounts/login/'

# LOGIN_REDIRECT_URL = '/'


# Remove modules used
del _os, _pathlib
